name: Release
on:
  release:
    types: [published]
env: 
  VERSION: ${{ github.event.release.tag_name }}
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  landing-build:
    name: Landing Page - build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-landing-page
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: landing
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7 
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  app-build:
    name: App - build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install dependencies
        run: cd wedding-app && yarn install
      - name: Build app
        run: cd wedding-app && yarn build
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-app
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: wedding-app
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7 
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  landing-deploy-homelab:
    name: Landing Page - deploy homelab
    runs-on: ubuntu-latest
    needs: landing-build
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      
      - name: Install Kubectl
        uses: azure/setup-kubectl@v1

      - name: Setup Context
        uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.HOME_LAB_KUBE_CONFIG }}

      - name: Deploy Application
        run: kubectl apply -f k8s/landing-homelab.yaml

      - name: Set Image
        run: kubectl set image deployments/wedding-landing-deployment -n wedding wedding-landing=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-landing-page:${{ env.VERSION }}
  landing-app-homelab:
    name: App Page - deploy homelab
    runs-on: ubuntu-latest
    needs: app-build
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      
      - name: Install Kubectl
        uses: azure/setup-kubectl@v1

      - name: Setup Context
        uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.HOME_LAB_KUBE_CONFIG }}

      - name: Deploy Application
        run: kubectl apply -f k8s/app-homelab.yaml

      - name: Set Image
        run: kubectl set image deployments/wedding-app-deployment -n wedding wedding-app=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-app:${{ env.VERSION }}